In [1]:
import numpy as np
import os
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
#from sklearn.model_selection import cross_validate

folderPath = '../stage1'
trainArray = np.load(os.path.join(folderPath,'train.npy'))
testArray = np.load(os.path.join(folderPath, 'test.npy'))

trainData = trainArray[:,0:-1]
trainLabel = trainArray[:,-1]

testData = testArray[:,0:-1]
testLabel = testArray[:,-1]

In [7]:
from IPython.display import Image  
import pydotplus
from sklearn.externals.six import StringIO

dt = tree.DecisionTreeClassifier(min_samples_split=10, random_state=99)
scores = cross_val_score(dt, trainData, trainLabel, cv=5)
#scoring = ['precision_macro', 'recall_macro']
#scores = cross_validate(dt, trainData, trainLabel, scoring=scoring, cv=5, return_train_score=False)
print (scores)
dt = dt.fit(trainData, trainLabel)
pred = dt.predict(testData)
acc = accuracy_score(testLabel, pred)
recall = recall_score(testLabel, pred)
f1Score = f1_score(testLabel, pred)
print (acc)
print (recall)
print (f1Score)

dot_data = StringIO()
tree.export_graphviz(dt, out_file=dot_data,  filled=True, rounded=True, special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

[ 0.95205707  0.95039814  0.95022399  0.94657375  0.95038991]
0.962790697674
0.665845648604
0.605675877521


InvocationException: GraphViz's executables not found

In [9]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_depth=40, min_samples_split=10, random_state=99)
scores = cross_val_score(RF, trainData, trainLabel, cv=5)

print (scores)
RF = RF.fit(trainData, trainLabel)
pred = RF.predict(testData)
acc = accuracy_score(testLabel, pred)
recall = recall_score(testLabel, pred)
f1Score = f1_score(testLabel, pred)
print (acc)
print (recall)
print (f1Score)

[ 0.95769741  0.95703384  0.95503567  0.95569935  0.95636303]
0.972093023256
0.638752052545
0.66269165247


In [4]:
from sklearn import svm
bSVM = svm.SVC(class_weight='balanced')
#bSVM = svm.LinearSVC()

#scores = cross_val_score(bSVM, trainData, trainLabel, cv=5)
#print (scores)
bSVM = bSVM.fit(trainData, trainLabel)
pred = bSVM.predict(testData)
acc = accuracy_score(testLabel, pred)
recall = recall_score(testLabel, pred)
f1Score = f1_score(testLabel, pred)
print (acc)
print (recall)
print (f1Score)

'''
rbf with balanced
0.96169837914
0.454844006568
0.504783599089'''

0.96169837914
0.454844006568
0.504783599089


'\nrbf with balanced\n0.96169837914\n0.454844006568\n0.504783599089'

In [23]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()

scores = cross_val_score(LR, trainData, trainLabel, cv=5)
print (scores)

LR = LR.fit(trainData, trainLabel)
pred = LR.predict(testData)
pred = np.where(pred >= 0.5, 1, 0)
acc = accuracy_score(testLabel, pred)
recall = recall_score(testLabel, pred)
f1Score = f1_score(testLabel, pred)
print (acc)
print (recall)
print (f1Score)

[ 0.31664441  0.30725766  0.31313958  0.29762914  0.31642995]
0.958386187456
0.114121510673
0.190541466758


In [14]:
from sklearn.linear_model import LogisticRegression
LogR = LogisticRegression(random_state=99, class_weight='balanced', penalty='l1', C=10000)

scores = cross_val_score(LogR, trainData, trainLabel, cv=5)
print (scores)

LogR = LogR.fit(trainData, trainLabel)
pred = LogR.predict(testData)
#pred = np.where(pred >= 0.5, 1, 0)
acc = accuracy_score(testLabel, pred)
recall = recall_score(testLabel, pred)
f1Score = f1_score(testLabel, pred)
print (acc)
print (recall)
print (f1Score)

[ 0.8384207   0.84041141  0.84071677  0.83407997  0.84221005]
0.846441155743
0.97619047619
0.353028503563


In [12]:
'''
countPos = 0
countNeg = 0
countTP = 0
index = 0;
for p,t in zip(pred,testLabel):
    if p!=t:
        countNeg+=1
    else :
        countPos+=1
    if t==1 and p==t:
        countTP+=1
    if t==1 and p!=t:
        print(index)
    index+=1
print(countPos,countNeg,float(countPos)/(countPos+countNeg))
print(countTP)
'''

'\ncountPos = 0\ncountNeg = 0\ncountTP = 0\nindex = 0;\nfor p,t in zip(pred,testLabel):\n    if p!=t:\n        countNeg+=1\n    else :\n        countPos+=1\n    if t==1 and p==t:\n        countTP+=1\n    if t==1 and p!=t:\n        print(index)\n    index+=1\nprint(countPos,countNeg,float(countPos)/(countPos+countNeg))\nprint(countTP)\n'